---
- name: install rsyslog package
  ansible.builtin.package:
    name: rsyslog
    state: present

- name: create ossec.conf file
  ansible.builtin.template:
    src: forward.conf.j2
    dest: /etc/rsyslog.d/forward.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart rsyslog

- name: start rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: yes
